name: Test JS Action

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Greeting Action
        id: greet-step
        uses: ./ 
        with:
          name: 'Sonu Sathyadas'

      - name: Verify Greeting Output
        run: |
          echo "The action said: ${{ steps.greet-step.outputs.greeting }}"